import plugintypes/[TACTI, TALCH, TAPPA, TARMO, TBODY, TBOOK, TBSGN, TCELL, TCLAS,
    TCLOT, TCONT, TCREA, TDIAL,
TDOOR, TENCH, TFACT, TGLOB, TGMST, TINFO, TINGR, TLAND, TLEVC, TLEVI, TLIGH,
    TLOCK, TLTEX,
TMGEF, TMISC, TNPC, TPGRD, TPROB, TRACE, TREGN, TREPA, TSCPT, TSKIL, TSNDG,
    TSOUN, TSPEL,
TSSCR, TSTAT, TTES3, TWEAP, record]

export TACTI, TALCH, TAPPA, TARMO, TBODY, TBOOK, TBSGN, TCELL, TCLAS, TCLOT,
    TCONT, TCREA, TDIAL, TDOOR, TENCH, TFACT, TGLOB, TGMST, TINFO, TINGR, TLAND,
    TLEVC, TLEVI, TLIGH, TLOCK, TLTEX, TMGEF, TMISC, TNPC, TPGRD, TPROB, TRACE,
    TREGN, TREPA, TSCPT, TSKIL, TSNDG, TSOUN, TSPEL, TSSCR, TSTAT, TTES3, TWEAP, record
